name: Auto Release from URLs

on:
  # Allow manual trigger from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for release (e.g. v1.0.0)'
        required: true
      release_name:
        description: 'Optional release name (defaults to tag name)'
        required: false

permissions:
  contents: write  # Required for creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download files from urls.txt
      - name: Download files from urls.txt
        run: |
          mkdir downloads
          while IFS= read -r url; do
            [ -z "$url" ] && continue  # skip empty lines
            echo "Downloading $url"
            curl -L "$url" -o "downloads/$(basename "$url")"
          done < urls.txt
          echo "Downloaded files:"
          ls -lh downloads/

      # Step 3: Create a GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.release_name || inputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload downloaded files as release assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: downloads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
