name: Auto Multi-Tag Release from CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install aria2
      - name: Install aria2
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2

      # Step 3: Check gh CLI
      - name: Check gh CLI
        run: gh --version

      # Step 4: Process CSV and upload
      - name: Process CSV and upload files
        run: |
          mkdir -p tmp

          # Skip CSV header line, iterate each row
          tail -n +2 files.csv | while IFS=, read -r tag filename url; do
            [ -z "$url" ] && continue

            echo "🟦 Tag: $tag"
            echo "⬇️  Downloading: $filename"
            echo "🔗 URL: $url"

            # Ensure release exists or create it
            if ! gh release view "$tag" >/dev/null 2>&1; then
              echo "🆕 Creating release for tag $tag"
              gh release create "$tag" \
                --title "$tag" \
                --notes "Automated release for tag $tag"
            fi

            # Download with retries and multi-threaded mode
            attempt=1
            max_attempts=10
            success=false
            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt of $max_attempts..."
              if aria2c -x16 -s16 -j1 -c --retry-wait=5 --max-tries=10 \
                -d tmp -o "$filename" "$url"; then
                success=true
                break
              fi
              attempt=$((attempt + 1))
              echo "⚠️  Download failed, retrying..."
              sleep 5
            done

            if [ "$success" = false ]; then
              echo "❌ Failed to download $filename after $max_attempts attempts."
              continue
            fi

            # Upload file to the corresponding release
            echo "⬆️  Uploading $filename to release $tag..."
            gh release upload "$tag" "tmp/$filename" --clobber
            rm -f "tmp/$filename"

            echo "✅ Successfully uploaded $filename to release $tag."
            echo "-----------------------------------------"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
