name: Auto Release from URLs

on:
  workflow_dispatch:  # allows manual trigger
  push:
    tags:
      - 'v*'  # or trigger when you push a version tag like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Read URLs and download files
      - name: Download files from urls.txt
        run: |
          mkdir downloads
          while IFS= read -r url; do
            echo "Downloading $url"
            curl -L "$url" -o "downloads/$(basename "$url")"
          done < urls.txt

      # Step 3: Create a GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload downloaded files as release assets
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: downloads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
