name: Auto Release from URLs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for release (e.g. v1.0.0)'
        required: true
      release_name:
        description: 'Optional release name (defaults to tag name)'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download all URLs and preserve real filenames
      - name: Download files from urls.txt
        run: |
          mkdir -p downloads
          cd downloads
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            echo "Downloading $url"
            curl -L -J -O "$url"
          done < ../urls.txt
          echo "Downloaded files:"
          ls -lh

      # Create or update the release
      - name: Create or update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.release_name || inputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload all downloaded files as release assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: downloads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
