name: Auto Release from CSV URLs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for release'
        required: true
      release_name:
        description: 'Optional release name'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install aria2
        run: sudo apt-get update && sudo apt-get install -y aria2

      - name: Check gh CLI
        run: gh --version

      - name: Create or update release
        run: |
          gh release view "${{ inputs.tag }}" >/dev/null 2>&1 || \
          gh release create "${{ inputs.tag }}" \
            --title "${{ inputs.release_name || inputs.tag }}" \
            --notes "Automated release for tag ${{ inputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download & upload files from CSV
        run: |
          mkdir -p tmp
          tail -n +2 files.csv | while IFS=, read -r filename url; do
            [ -z "$url" ] && continue
            echo "⬇️ Downloading $filename from $url"

            # Download with aria2c, retries, multi-threaded
            aria2c -x16 -s16 -j1 -c --retry-wait=5 --max-tries=10 \
              -d tmp -o "$filename" "$url"

            # Upload to GitHub release
            gh release upload "${{ inputs.tag }}" "tmp/$filename" --clobber
            rm -f "tmp/$filename"
            echo "✅ Uploaded $filename successfully."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
